### ISSUE TITLE
Where can I use the code "Column fixed"? In code block or css?

### ISSUE THREAD

**Issue by jordanmaxis** [valentine195/fantasy-statblocks#109]
My sheet is always straight as a board, and never bend to another column. I wonder how can I adjust it to another column?

**Comment by nonzer0value** [comment]
I think this is in the [README](https://github.com/valentine195/obsidian-5e-statblocks#columns).

**Comment by sigrunixia** [comment]
Specifically, here are all the column settings with some pre-defined values. 

forceColumns will always force the amount of columns defined in columns.

```yaml
columns: 2
forceColumns: true
columnHeight: 750px
columnWidth: 550px
```

Closing due to age.
