### ISSUE TITLE
[Question] Nested Trait Lists?

### ISSUE THREAD

**Issue by freohr** [valentine195/fantasy-statblocks#174]
Hello again, 

How feasible would it be to enable or do nested traits list? Maybe not unlimited nesting, maybe only 1 or 2 additional levels?

In 13th Age, monsters' attacks can have added effect depending on the die roll, and the effects are listed below the corresponding attack in the stat-block like this 
![image](https://user-images.githubusercontent.com/3462951/232339610-7663d5cf-c218-4c45-b746-3cfd90de6a75.png)

and I would like to be able to easily write that in the YAML block without needing to write a custom block that could break the overall styling (like multi-columns on big stat-blocks)

Suggested YAML format

```yaml
attacks:
    - name: Fang, Claws and Horns +14 vs. AC (3 attacks)
      desc: 25 damage per hit
      traits:
          - name: Natural 14-15
            desc: The target is dazed until the end of the Chimera's next turn from a headbutt
          - name: Natural 16-17
            desc: The target takes 20 ongoing damage from raking claws
          - name: Natural 18-20
            desc: The chimera makes a _Fiery Breath_ attack as a free action
```
